### ISSUE TITLE
Add "App preview" button to Viewer

### ISSUE THREAD

**Issue by thekarel** [guardian/editorial-viewer#44]
Provide a new button that fires off an email with app preview links (below).

Preview URL examples:
- iOS `https://entry.mobile-apps.guardianapis.com/deeplink/items/film/2016/feb/16/the-record`
- Android: `http://preview.mobile-apps.guardianapis.com/items/us-news/live/2016/jan/22/trump-mum-on-palin-rumors`

**Branch: `feature/44-app-preview-button`**

**ToDo:**
- [x] UI work @thekarel 
- [x] Back end: expose send email endpoint  @currysoup 
- [x] Connect UI to API call @currysoup
